# Chapter 4
## Numpy Arrays

In [1]:
import numpy as np

square = np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15],
     [16,17,18,19,20],
     [21,22,23,24,25]]
)

size=5

In [2]:
# This one is a bit hard to hold in the head - it's really easy to get the indexes wrong
spiral = []

for i in range(0, size):
    # Convert each part marked by any red arrow to a list
    spiral += list(square[i, i:size-i])
    
    # Convert each part marked by any green arrow to a list
    spiral += list(square[i+1:size-i, size-i-1])
    
    # Convert each part marked by any blue arrow to a list
    spiral += list(reversed(square[size-i-1, i:size-i-1]))
    
    # Convert each part marked by any magenta arrow to a list
    spiral += list(reversed(square[i+1:size-i-1, i]))
        
print(spiral)

[1, 2, 3, 4, 5, 10, 15, 20, 25, 24, 23, 22, 21, 16, 11, 6, 7, 8, 9, 14, 19, 18, 17, 12, 13]


In [3]:
input_list1 = [[1,2,3], [4,5,6], [7,8,9]]
input_array1 = np.array(input_list1)

# Substitute the code in the block 1 given the input_array1
output_array1 = input_array1 * 5 
print(list(map(lambda x: [5*i for i in x], input_list1)))
print(output_array1)

[[5, 10, 15], [20, 25, 30], [35, 40, 45]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [4]:
input_list2 = list(range(10))
input_array2 = np.array(input_list2)

In [5]:
# Substitute the code in the block 2 given the input_array2
output_array2 = input_array2[input_array2 % 2 == 0]
print(list(filter(lambda x: x % 2 == 0, input_list2)))
print(output_array2)

[0, 2, 4, 6, 8]
[0 2 4 6 8]


In [6]:
input_list3 = []
row = []
for i in range(1,7):
    row.append(i)
    if len(row) == 2:
        input_list3.append(row)
        row = []
print(input_list3)

input_array3 = np.array(input_list3)

[[1, 2], [3, 4], [5, 6]]


In [7]:
# Substitute the code in the block 3 given the input_array3
output_array3 = input_array3 ** 2
print([[i*i for i in j] for j in input_list3])
print(output_array3)

[[1, 4], [9, 16], [25, 36]]
[[ 1  4]
 [ 9 16]
 [25 36]]


## Dataframe

In [8]:
from functools import reduce
import pandas as pd

from urllib.request import urlretrieve
url = 'https://assets.datacamp.com/production/repositories/4298/datasets/d77902052165a763cc4bc84e2457e1f41e80d233/exams.csv'
file = 'exams.csv'
urlretrieve(url, file)

scores = pd.read_csv(file)

In [14]:
scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
gender                         100 non-null object
race/ethnicity                 100 non-null object
parental level of education    100 non-null object
lunch                          100 non-null object
test preparation course        100 non-null object
math score                     100 non-null int64
reading score                  100 non-null int64
writing score                  100 non-null int64
dtypes: int64(3), object(5)
memory usage: 6.3+ KB


In [15]:
groups_to_consider = ['gender',
                      'race/ethnicity',
                      'parental level of education',
                      'lunch',
                      'test preparation course']

In [28]:
def prevalence(series):
    vals = list(series)
    # Create a tuple list with unique items and their counts
    itms = [(x, series.value_counts()[x]) for x in set(series)]
    
    # Extract a tuple with the highest counts using reduce()
    res = reduce(lambda x, y: x if x[1] > y[1] else y, itms)
    
    # Return the item with the highest counts
    return res[0]
    
result = scores[groups_to_consider].apply(prevalence)
print(result)

gender                               female
race/ethnicity                      group C
parental level of education    some college
lunch                              standard
test preparation course                none
dtype: object


In [29]:
def rank(series):
    # Calculate the mean of the input series
    mean = series.mean()
    # Return the mean and its rank as a list
    if mean <= 60:
        return [mean, 'low']
    if mean > 90:
        return [mean, 'high']
    return [mean, 'medium']

In [38]:
# Insert the output of rank() into new columns of scores
cols = ['math score', 'reading score', 'writing score']
scores[['mean', 'rank']] = scores[cols].apply(rank, axis=1, result_type='expand')
print(scores[['mean', 'rank']].head())

        mean    rank
0  80.666667  medium
1  48.666667     low
2  47.666667     low
3  91.666667    high
4  82.333333  medium


In [40]:
def rescale(series, low, high):
    # Define the expression to rescale input series
    return (series/100 * (high-low)) + low

cols = ['math score', 'reading score', 'writing score']
scores[cols] = scores[cols].apply(rescale, args=[1,10], axis=1, result_type='expand')
print(scores[cols].head())

   math score  reading score  writing score
0        7.66           8.74           8.38
1        4.96           5.41           5.77
2        5.86           5.14           4.87
3        8.92           9.55           9.28
4        8.65           8.29           8.29


In [41]:
def rescale(series, low=0, high=100):
    # Define the expression to rescale input series
    return (series/100 * (high-low)) + low

cols = ['math score', 'reading score', 'writing score']
scores[cols] = scores[cols].apply(rescale, args=[1,10], axis=1, result_type='expand')
print(scores[cols].head())

   math score  reading score  writing score
0      1.6894         1.7866         1.7542
1      1.4464         1.4869         1.5193
2      1.5274         1.4626         1.4383
3      1.8028         1.8595         1.8352
4      1.7785         1.7461         1.7461


### Groupby

In [44]:
url = 'https://assets.datacamp.com/production/repositories/4298/datasets/203ff6d8dd61bede3cbac6fffdd77a222177f478/diabetes.csv'
file = 'diabetes.csv'
urlretrieve(url, file)

In [48]:
# Load the data from the diabetes.csv file
diabetes = pd.read_csv(file)
print(diabetes.info())

# Calculate the mean glucose level in the entire dataset
print(diabetes['plasma glucose'].mean())

# Group the data according to the diabetes test results
diabetes_grouped = diabetes.groupby('test result')

# Calculate the mean glucose levels per group
print(diabetes_grouped.agg('mean')['plasma glucose'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
n pregnant           768 non-null int64
plasma glucose       763 non-null float64
blood pressure       733 non-null float64
skin thickness       541 non-null float64
serum insulin        394 non-null float64
bmi                  757 non-null float64
pedigree function    768 non-null float64
age                  768 non-null int64
test result          768 non-null object
dtypes: float64(6), int64(2), object(1)
memory usage: 54.1+ KB
None
121.6867627785059
test result
negative    110.643863
positive    142.319549
Name: plasma glucose, dtype: float64


In [50]:
url = 'https://assets.datacamp.com/production/repositories/4298/datasets/58a461693fbca1f972a11024c3873004b102160c/heroes_information.csv'
file = 'heroes.csv'
urlretrieve(url, file)
heroes = pd.read_csv(file)
heroes.info()

heroes['bmi'] = heroes['Weight'] / (heroes['Height']/100)**2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 734 entries, 0 to 733
Data columns (total 11 columns):
Unnamed: 0    734 non-null int64
name          734 non-null object
Gender        734 non-null object
Eye color     734 non-null object
Race          734 non-null object
Hair color    734 non-null object
Height        734 non-null float64
Publisher     719 non-null object
Skin color    734 non-null object
Alignment     734 non-null object
Weight        732 non-null float64
dtypes: float64(2), int64(1), object(8)
memory usage: 63.2+ KB


In [52]:
heroes['Height']

0      203.0
1      191.0
2      185.0
3      203.0
4      -99.0
5      193.0
6      -99.0
7      185.0
8      173.0
9      178.0
10     191.0
11     188.0
12     193.0
13     180.0
14     -99.0
15     -99.0
16     178.0
17     244.0
18     -99.0
19     257.0
20     188.0
21     -99.0
22     183.0
23     -99.0
24     165.0
25     163.0
26     -99.0
27     183.0
28     180.0
29     211.0
       ...  
704    183.0
705    185.0
706    180.0
707    188.0
708    173.0
709    218.0
710    163.0
711    -99.0
712    -99.0
713    -99.0
714    178.0
715    -99.0
716    175.0
717    140.0
718    366.0
719    160.0
720    165.0
721    188.0
722    183.0
723    -99.0
724    196.0
725    155.0
726    175.0
727    188.0
728    183.0
729    165.0
730    304.8
731     66.0
732    170.0
733    185.0
Name: Height, Length: 734, dtype: float64

In [ ]:
import numpy as np

# Group the data by two factors specified in the context
groups = 

# Filter groups having more than 10 valid bmi observations
fheroes = 