# Chapter 4
## Numpy Arrays

In [4]:
import numpy as np

square = np.array(
    [[1,2,3,4,5],
     [6,7,8,9,10],
     [11,12,13,14,15],
     [16,17,18,19,20],
     [21,22,23,24,25]]
)

size=5

In [26]:
# This one is a bit hard to hold in the head - it's really easy to get the indexes wrong
spiral = []

for i in range(0, size):
    # Convert each part marked by any red arrow to a list
    spiral += list(square[i, i:size-i])
    
    # Convert each part marked by any green arrow to a list
    spiral += list(square[i+1:size-i, size-i-1])
    
    # Convert each part marked by any blue arrow to a list
    spiral += list(reversed(square[size-i-1, i:size-i-1]))
    
    # Convert each part marked by any magenta arrow to a list
    spiral += list(reversed(square[i+1:size-i-1, i]))
        
print(spiral)

[1, 2, 3, 4, 5, 10, 15, 20, 25, 24, 23, 22, 21, 16, 11, 6, 7, 8, 9, 14, 19, 18, 17, 12, 13]


In [27]:
input_list1 = [[1,2,3], [4,5,6], [7,8,9]]
input_array1 = np.array(input_list1)

# Substitute the code in the block 1 given the input_array1
output_array1 = input_array1 * 5 
print(list(map(lambda x: [5*i for i in x], input_list1)))
print(output_array1)

[[5, 10, 15], [20, 25, 30], [35, 40, 45]]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [28]:
input_list2 = list(range(10))
input_array2 = np.array(input_list2)

In [29]:
# Substitute the code in the block 2 given the input_array2
output_array2 = input_array2[input_array2 % 2 == 0]
print(list(filter(lambda x: x % 2 == 0, input_list2)))
print(output_array2)

[0, 2, 4, 6, 8]
[0 2 4 6 8]


In [37]:
input_list3 = []
row = []
for i in range(1,7):
    row.append(i)
    if len(row) == 2:
        input_list3.append(row)
        row = []
print(input_list3)

input_array3 = np.array(input_list3)

[[1, 2], [3, 4], [5, 6]]


In [38]:
# Substitute the code in the block 3 given the input_array3
output_array3 = input_array3 ** 2
print([[i*i for i in j] for j in input_list3])
print(output_array3)

[[1, 4], [9, 16], [25, 36]]
[[ 1  4]
 [ 9 16]
 [25 36]]


## Dataframe

In [40]:
from functools import reduce
import pandas as pd

from urllib.request import urlretrieve
url = 'https://assets.datacamp.com/production/repositories/4298/datasets/d77902052165a763cc4bc84e2457e1f41e80d233/exams.csv'
file = 'exams.csv'
urlretrieve(url, file)

scores = pd.read_csv(file)

In [42]:
scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   gender                       100 non-null    object
 1   race/ethnicity               100 non-null    object
 2   parental level of education  100 non-null    object
 3   lunch                        100 non-null    object
 4   test preparation course      100 non-null    object
 5   math score                   100 non-null    int64 
 6   reading score                100 non-null    int64 
 7   writing score                100 non-null    int64 
dtypes: int64(3), object(5)
memory usage: 6.4+ KB


In [43]:
groups_to_consider = ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course']

In [53]:
def prevalence(series):
    vals = list(series)
    # Create a tuple list with unique items and their counts
    itms = [(x, series.unique()[x]) for x in set(series)]
    print(itms)
    # Extract a tuple with the highest counts using reduce()
    #res = reduce(lambda x, y: ____, ____)
    # Return the item with the highest counts
    #return res[-1]
    
#prevalence(scores['gender'])

scores['gender'].count('male')

KeyError: 'Requested level (male) does not match index name (None)'

In [ ]:
def prevalence(series):
    vals = list(series)
    # Create a tuple list with unique items and their counts
    itms = [(x, count(x)) for x in set(series)]
    # Extract a tuple with the highest counts using reduce()
    res = reduce(lambda x, y: ____, ____)
    # Return the item with the highest counts
    return res[-1]

# Apply the prevalence function on the scores DataFrame
result = scores[groups_to_consider].apply(prevalence)
print(result)