<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from urllib.request import urlretrieve
from io import StringIO

In [2]:
# Import the LocalOutlierFactor module
from sklearn.neighbors import LocalOutlierFactor as lof

# Create the list [1.0, 1.0, ..., 1.0, 10.0] as explained
x = [1.0]*30
x.append(10)

# Cast to a data frame
X = pd.DataFrame(x)

# Fit the local outlier factor and print the outlier scores
print(lof().fit_predict(X))

[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1
  1  1  1  1  1  1 -1]


/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/neighbors/lof.py:236: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)


In [15]:
file = 'arrh.csv'
url = 'https://assets.datacamp.com/production/repositories/3554/datasets/eb59119dbc87d95d89b446b825cb38854a59411e/'
urlretrieve(url+file, file)
arrh = pd.read_csv(file)

target = 'class'

X = arrh.drop(target, axis=1)
y = arrh[target]

ground_truth = y.copy()
idx = ground_truth == 0
ground_truth[idx] = -1

from sklearn.metrics import confusion_matrix

In [16]:
# Fit the local outlier factor and output predictions
preds = lof().fit_predict(X)

# Print the confusion matrix
print(confusion_matrix(ground_truth, preds))

[[ 40 167]
 [  6 239]]


/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/neighbors/lof.py:236: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)


In [38]:
# Fit the local outlier factor and output predictions
preds = lof(contamination=0.2).fit_predict(X)

# Print the confusion matrix
print(confusion_matrix(ground_truth, preds))

[[ 72 135]
 [ 19 226]]


In [37]:
# Fit the local outlier factor and output predictions
preds = lof(contamination=np.mean(ground_truth == -1)).fit_predict(X)

# Print the confusion matrix
print(confusion_matrix(ground_truth, preds))

[[141  66]
 [ 66 179]]


In [39]:
# Create a list of thirty 1s and cast to a dataframe
X = pd.DataFrame([1.0]*30)

# Create an instance of a lof novelty detector
detector = lof(novelty=True)

# Fit the detector to the data
detector.fit(X)

# Use it to predict the label of an example with value 10.0
print(detector.predict(pd.DataFrame([10])))

[-1]


/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/neighbors/lof.py:236: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)


In [43]:
from sklearn.model_selection import train_test_split

arrh = pd.read_csv(file)

target = 'class'

X = arrh.drop(target, axis=1)
y = arrh[target]

ground_truth = y.copy()
idx = ground_truth == 0
ground_truth[idx] = -1

from sklearn.metrics import confusion_matrix
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [49]:
# Import the novelty detector
from sklearn.svm import OneClassSVM as onesvm

# Fit it to the training data and score the test data
svm_detector = onesvm().fit(X_train)
scores = svm_detector.score_samples(X_test)

/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [51]:
# Import the novelty detector
from sklearn.ensemble import IsolationForest as isof

# Fit it to the training data and score the test data
isof_detector = isof().fit(X_train)
scores = isof_detector.score_samples(X_test)

/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/ensemble/iforest.py:237: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/ensemble/iforest.py:247: FutureWarning: behaviour="old" is deprecated and will be removed in version 0.22. Please use behaviour="new", which makes the decision_function change to match other anomaly detection algorithm API.
  FutureWarning)


In [53]:
# Import the novelty detector
from sklearn.neighbors import LocalOutlierFactor as lof

# Fit it to the training data and score the test data
lof_detector = lof(novelty=True).fit(X_train)
scores = lof_detector.score_samples(X_test)

/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/neighbors/lof.py:236: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)


In [76]:
from sklearn.svm import OneClassSVM as onesvm
onesvm

sklearn.svm.classes.OneClassSVM

In [77]:
# Fit a one-class SVM detector and score the test data
nov_det = onesvm().fit(X_train)
scores = nov_det.score_samples(X_test)

# Find the observed proportion of outliers in the test data
prop = np.mean(y_test==1)

# Compute the appropriate threshold
threshold = np.quantile(X_test, prop)

# Print the confusion matrix for the thresholded scores
print(confusion_matrix(y_test, scores > threshold))

[[48  4]
 [52  9]]


/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [97]:
file = 'hep.csv'
url = 'https://assets.datacamp.com/production/repositories/3554/datasets/7a8662884e2157642c3eb287bee39346040c8bef/'
urlretrieve(url+file, file)
df = pd.read_csv(file)

target = 'Class'
X = df.drop(target, axis=1)
y = df[target]

features = X[50:54]
labels = y[50:54]

In [98]:
# Import DistanceMetric as dm
from sklearn.neighbors import DistanceMetric as dm

In [99]:
# Import DistanceMetric as dm
from sklearn.neighbors import DistanceMetric as dm

# Find the Euclidean distance between all pairs
dist_eucl = dm.get_metric('euclidean').pairwise(features)

# Find the Hamming distance between all pairs
dist_hamm = dm.get_metric('hamming').pairwise(features)

# Find the Chebyshev distance between all pairs
dist_cheb = dm.get_metric('chebyshev').pairwise(features)

In [108]:
dist_eucl[0,:], labels

(array([  0.        , 129.70119506, 197.95638408, 104.38036214]), 50    2.0
 51    1.0
 52    2.0
 53    2.0
 Name: Class, dtype: float64)

In [107]:
dist_hamm[0,:], labels

(array([0.        , 0.47368421, 0.63157895, 0.52631579]), 50    2.0
 51    1.0
 52    2.0
 53    2.0
 Name: Class, dtype: float64)

In [106]:
dist_cheb[0,], labels

(array([  0., 123., 190.,  83.]), 50    2.0
 51    1.0
 52    2.0
 53    2.0
 Name: Class, dtype: float64)

In [110]:
from sklearn.neighbors import LocalOutlierFactor as lof

In [121]:
# Compute outliers according to the euclidean metric
out_eucl = lof(metric='euclidean').fit_predict(features)

# Compute outliers according to the hamming metric
out_hamm = lof(metric='hamming').fit_predict(features)

# Compute outliers according to the jaccard metric
out_jacc  = lof(metric='jaccard').fit_predict(features)

# Find if the metrics agree on any one datapoint
print(any(out_eucl + out_hamm + out_jacc == -3))

False


/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/neighbors/lof.py:236: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/neighbors/lof.py:253: UserWarning: n_neighbors (20) is greater than the total number of samples (4). n_neighbors will be set to (n_samples - 1) for estimation.
  % (self.n_neighbors, n_samples))
/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/neighbors/lof.py:236: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)
/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/neighbors/lof.py:253: UserWarning: n_neighbors (20) is greater than the total number of samples (4). n_neighbors will be set to (n_samples - 1) for estimation.
  %

In [229]:
file = 'proteins_exercises.csv'
url = 'https://assets.datacamp.com/production/repositories/3554/datasets/76399b36f4b8a83a3a441f39cf1cc1171171db5c/'
urlretrieve(url+file, file)

proteins = pd.read_csv(file)
proteins.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
label    100 non-null object
seq      100 non-null object
dtypes: object(2)
memory usage: 1.6+ KB


In [230]:
import stringdist
from sklearn.neighbors import LocalOutlierFactor as lof
from sklearn.metrics import accuracy_score as accuracy
from scipy.spatial.distance import pdist, squareform

In [231]:
# Wrap the RD-Levenshtein metric in a custom function
def my_rdlevenshtein(u, v):
    return stringdist.rdlevenshtein(u[0], v[0])

# Reshape the array into a numpy matrix
sequences = np.array(proteins['seq']).reshape(-1, 1)

# Compute the pairwise distance matrix in square form
M = squareform(pdist(sequences, metric=my_rdlevenshtein))

# Run a LoF algorithm on the precomputed distance matrix
preds = lof(metric='precomputed').fit_predict(M)

# Compute the accuracy of the outlier predictions
print(accuracy(proteins['label'] == 'VIRUS', preds==-1))

0.82


/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/neighbors/lof.py:236: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)


In [236]:
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import roc_auc_score as auc
from sklearn.neighbors import LocalOutlierFactor
from sklearn.model_selection import train_test_split

lof_detector = LocalOutlierFactor(novelty=True, metric='precomputed').fit(M)

/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/neighbors/lof.py:236: FutureWarning: default contamination parameter 0.1 will change in version 0.22 to "auto". This will change the predict method behavior.
  FutureWarning)


In [241]:
# Create a feature that contains the length of the string
proteins['len'] = proteins['seq'].apply(len)

# Create a feature encoding the first letter of the string
proteins['first'] =  LabelEncoder().fit_transform(
    proteins['seq'].apply(lambda s: list(s)[0]))

# Extract scores from the fitted LoF object, compute its AUC
scores_lof = lof_detector.negative_outlier_factor_
print(auc(proteins['label']=='IMMUNE SYSTEM', scores_lof))

# Fit a 1-class SVM, extract its scores, and compute its AUC
svm = OneClassSVM().fit(proteins[['len', 'first']])
scores_svm = svm.score_samples(proteins[['len', 'first']])
print(auc(proteins['label']=='IMMUNE SYSTEM', scores_svm))

0.739375
0.5884375


/Users/Brian/anaconda3/envs/datacamp/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
